version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6005:5432"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
