version: "3.7"
services:
  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "6005:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -d ${PG_DATABASE:-postgres} -U ${PG_USERNAME:-postgres}"
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 60s

  waitForDb:
    image: alpine:3.17.3
    depends_on: 
      postgres: 
        condition: service_healthy

  npm-registry:
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    volumes:
      - ./config/config.yaml:/verdaccio/conf/config.yaml:ro

volumes:
  postgres-data:
